//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductIngredient
    {
        public int Id { get; set; }
        public int Product { get; set; }
        public int Ingredient { get; set; }
        public int Quantity { get; set; }
    
        public virtual Ingredient Ingredient1 { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
